site_name: Documentació Model Optimització
site_url: https://mysite.com
theme:
  name: material
  palette: 
    primary: grey
    accent: brown


markdown_extensions:
  - admonition
  # Se recomienda también para anidamiento y otras características:
  - pymdownx.details
  - pymdownx.superfences
  - tables

extra_javascript:
  - javascripts/export-table.js