site_name: Documentació Model Optimització
site_url: https://mysite.com
theme:
  name: material


markdown_extensions:
  - admonition
  # Se recomienda también para anidamiento y otras características:
  - pymdownx.details
  - pymdownx.superfences